### ISSUE TITLE
card colors are not correct when using custom values

### ISSUE THREAD

**Issue by nathanloyer** [hellomuthu23/planning-poker#106]
If you use a custom set of cards, then the color matching for displaying player votes is broken. To reproduce, create a new session with custom values. Then try out voting a few times to see the color codes. I have only ever seen the light blue color or gray when doing this. The display should match the colors at the bottom of the page.

**Comment by hellomuthu23** [comment]
Great find @nathanloyer!. I have fixed it now. Thanks for reporting it, highly appreciated!

**Comment by nathanloyer** [comment]
Thanks for the quick fix. I was using this with my team earlier this week with custom values and trying to figure out how the color coding was supposed to work :D It never made any sense!

Thanks again, it's a very nice tool overall
