### ISSUE TITLE
Can't see everyone when there are lots of people in the room

### ISSUE THREAD

**Issue by BradPatras** [hellomuthu23/planning-poker#46]
We've got 19 people in the current session and the container won't scroll far enough to the left to show everyone, there are 3 people that are still off-screen when scrolled all the way to the left.  

Tested on chrome and safari and the issue is on both.  If I zoom out to 70% then I can see everyone.

**Comment by hellomuthu23** [comment]
#47

**Comment by hellomuthu23** [comment]
Thanks for reporting the issue, fixed now to show all people in the scroll area.
