### ISSUE TITLE
Not limit the reveal feature to the moderator only

### ISSUE THREAD

**Issue by alvarocasta** [hellomuthu23/planning-poker#92]
My team is currently using this amazing tool for our estimations. We use the same room every week, so the URL can be added to the calendar event.

However, we encounter problems when the moderator doesn't join the session. Cards cannot be revealed.
Is there any way to allow any participant to act as a moderator? Basically, it is to remove any restrictions so all participants can run the session if needed.

Thanks and congrats! we love the tool!

**Comment by hellomuthu23** [comment]
@alvarocasta  - Thanks for reaching out with your feedback. This is a good idea, It will be hard to provide this feature to existing sessions. I can think of adding an option `Allow any members to reveal`  while creating the session, so when someone creating a session and wishes any of the members to reveal as well, they can choose this new option.

**Comment by alvarocasta** [comment]
that would be amazing @hellomuthu23! I wouldn't expect this to happen for the existing sessions either.

**Comment by hellomuthu23** [comment]
@alvarocasta this feature is live now. Thanks again for the feedback
