### ISSUE TITLE
Feature Request: Option to disable Question mark, and emoji cards

### ISSUE THREAD

**Issue by jamesr981** [hellomuthu23/planning-poker#98]
In the game creation settings, I'd like 2 new options or similar to allow the Question mark, and random emoji cards in the games.

Reasoning:
I don't want my team to just say 'I don't know', or try to be funny by only using the emoji card.

Thanks!

**Comment by hellomuthu23** [comment]
> In the game creation settings, I'd like 2 new options or similar to allow the Question mark, and random emoji cards in the games.
> 
> Reasoning: I don't want my team to just say 'I don't know', or try to be funny by only using the emoji card.
> 
> Thanks!

Good point! I will check if I can remove them from the custom card creation.

**Comment by hellomuthu23** [comment]
Emoji and Question cards are removed from custom cards now, you can create new custom card session with your own options now.
